server:
  port: 8080

spring:
  application:
    name: oomall
  profiles:
    active: test
  output:
    ansi:
      enabled: detect

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info

mybatis:
  #domain对象的包
  type-aliases-package: xmu.oomall.domain
  #mapper。xml所在的位置
  mapper-locations: classpath:xmu.oomall.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

logging:
  #设置日志打印级别
  level:
    root: warn
    xmu.omomall: warn
  #使用logback日志，取代默认的common日志

